Rails.application.config.assets.precompile += %w( shared.js )
Rails.application.config.assets.precompile += %w( bootstrap.css )
Rails.application.config.assets.precompile += %w( underscore.js )
Rails.application.config.assets.precompile += %w( jquery.cycle.all.js )
Rails.application.config.assets.precompile += %w( gmaps/google.js )